# Copyright 2019 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  push:
    branches:
    - main

name: Build and Deploy to Cloud Run
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  REACTCOREDEMOSVC: reactcoredemosvc
  REGION: australia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true


    - name: Build and Push Container For ${{ env.REACTCOREDEMOSVC }}
      run: |-
        cd Metro60Functions
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.REACTCOREDEMOSVC }}:${{ github.sha }} . --file Demo_React_App/Dockerfile
    
    - name: Authorize Docker push For ${{ env.REACTCOREDEMOSVC }}
      run: gcloud auth configure-docker -q
      
    - name: Push for ${{ env.REACTCOREDEMOSVC }}
      run: |-
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.REACTCOREDEMOSVC }}:${{  github.sha }}
        
    - name: Deploy to Cloud Run for ${{ env.REACTCOREDEMOSVC }}
      run: |-
        gcloud run deploy ${{ env.REACTCOREDEMOSVC }} \
          --region ${{ env.REGION }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.REACTCOREDEMOSVC }}:${{  github.sha }} \
          --platform "managed" \
          --quiet
